version: "3.4"

services:
  #  zookeeper:
  #    container_name: axon-techbank-zookeeper
  #    image: bitnami/zookeeper
  #    restart: always
  #    ports:
  #      - "2181:2181"
  #    volumes:
  #      - "zookeeper-data:/bitnami"
  #    environment:
  #      - ALLOW_ANONYMOUS_LOGIN=yes
  #  kafka:
  #    container_name: axon-techbank-kafka
  #    image: bitnami/kafka
  #    ports:
  #      - "9092:9092"
  #    restart: always
  #    volumes:
  #      - "kafka-data:/bitnami"
  #    environment:
  #      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #      - ALLOW_PLAINTEXT_LISTENER=yes
  #      - KAFKA_LISTENERS=PLAINTEXT://:9092
  #      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #    depends_on:
  #      - zookeeper
  mysql:
    container_name: axon-techbank-mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "mysql-data:/var/lib/mysql"
  axonserver:
    container_name: axon-techbank-axonserver
    image: axoniq/axonserver
    hostname: axonserver
    restart: always
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
  mongo:
    container_name: axon-techbank-mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodb-data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  postgresql:
    container_name: axon-techbank-postgresql
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5433:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: axon-techbank-account-query
  postgresql-adminer:
    container_name: axon-techbank-pgadminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: axon-techbank-postgresql
volumes:
  #  zookeeper-data:
  #    driver: local
  #  kafka-data:
  #    driver: local
  mongodb-data:
    driver: local
  postgresql-data:
    driver: local
  mysql-data:
    driver: local
  axonserver-data:
    driver: local
  axonserver-events:
    driver: local
  axonserver-config:
    driver: local

networks:
  default:
    external:
      name: axon-techbank-net
