server:
  port: 8282

eureka:
  instance:
    prefer-ip-address: true # registers the service ip rather than the server name
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8761/eureka # discovery service location

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-command-service
          uri: lb://account-command-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: account-query-service
          uri: lb://account-query-service
          predicates:
            - Path=/api/v1/query-accounts/**
