server:
  port: 5001
spring:
  application:
    name: account-query-service # current service name used for eureka registration
  data:
    mongodb:
      database: axon-techbank-account-command
      host: localhost
      port: 27017
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5433/axon-techbank-account-query
    username: postgres
    password: 123456

eureka:
  instance:
    prefer-ip-address: true # registers the service ip rather than the server name
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8761/eureka # discovery service location



